### ISSUE TITLE
Is this still supported? is this run via docker?

### ISSUE THREAD

**Issue by captainnapalm** [Zibbp/navidrome-utils#1]
Hello, I'm looking to run your tidal-utils and navidrome-utils repos. tidal-utils has specific docker-compose instructions, but navidrome-utils is pretty sparse on instructions on how to run.

**Comment by Zibbp** [comment]
Hi,
I would use the newer https://github.com/Zibbp/music-utils repo that combines the two. I need to archive the older repos.

**Comment by captainnapalm** [comment]
oh, awesome! Thanks!
